import Header from './components/header/header';
import Head from 'next/head';
import Footer from './components/footer/footer';

export const getStaticPaths = async () => {
	const res = await fetch('http://localhost:1337/hotels');
	const data = await res.json();

	const paths = data.map((hotel) => {
		return {
			params: { id: hotel.id.toString() },
		};
	});

	return {
		paths,
		fallback: false,
	};
};

export const getStaticProps = async (context) => {
	const id = context.params.id;
	const res = await fetch('http://localhost:1337/hotels/' + id);
	const data = await res.json();

	return {
		props: { hotels: data },
	};
};

const HotelDetails = ({ hotels: { title, imageUrl, price, adress } }) => {
	return (
		<>
			<Head>
				<title>Holidaze</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
				<link
					rel="apple-touch-icon"
					sizes="180x180"
					href="/apple-touch-icon.png"
				/>
				<link
					rel="icon"
					type="image/png"
					sizes="32x32"
					href="/favicon-32x32.png"
				/>
				<link
					rel="icon"
					type="image/png"
					sizes="16x16"
					href="/favicon-16x16.png"
				/>
			</Head>
			<Header />
			<main>
				<div className="details_wrapper">
					<div className="details_header">
						<div>
							<h1>{title}</h1>
							<p>{adress}</p>
							<p></p>
						</div>
					</div>
				</div>
			</main>
			<Footer />
		</>
	);
};

export default HotelDetails;
