import Head from 'next/head';
import Footer from '../components/footer/footer';
import { Navbar } from '../components/header/header';
import Image from 'next/image';

import React from 'react';
import { Formik, Form, Field } from 'formik';
import * as Yup from 'yup';

import axios from 'axios';
import { useRouter } from 'next/router';
import { BASEURL } from '../components/lib/variables';

const SignupSchema = Yup.object().shape({
	firstname: Yup.string()
		.min(2, 'Too Short!')
		.max(50, 'Too Long!')
		.required('Required'),
	lastname: Yup.string()
		.min(2, 'Too Short!')
		.max(50, 'Too Long!')
		.required('Required'),
	message: Yup.string()
		.min(2, 'Too Short!')
		.max(50, 'Too Long!')
		.required('Required'),
	email: Yup.string().email('Invalid email').required('Required'),
});

export default function Home() {
	const router = useRouter();
	return (
		<>
			<Head>
				<title>Holidaze</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />

				<link
					rel="apple-touch-icon"
					sizes="180x180"
					href="/apple-touch-icon.png"
				/>
				<link
					rel="icon"
					type="image/png"
					sizes="32x32"
					href="/favicon-32x32.png"
				/>
				<link
					rel="icon"
					type="image/png"
					sizes="16x16"
					href="/favicon-16x16.png"
				/>
			</Head>
			<Navbar />
			<main>
				<div className="contact_wrapper">
					<div className="contact_ImgContainer">
						<Image
							className="contactImg"
							src="/img/hotelsbg.png"
							layout="fill"
							alt="Green background with the logo of holdidaze repeated multipel times"
						/>
						<h1>We are here to help</h1>
					</div>
					<div className="contact_formContainer">
						<div className="contact_headingBox">
							<h1>Contact form</h1>
							<h2>Lets get in touch</h2>
						</div>

						<Formik
							initialValues={{
								firstname: '',
								lastname: '',
								email: '',
								message: '',
							}}
							validationSchema={SignupSchema}
							onSubmit={(newMessage) => {
								async function postdata() {
									let response = await axios.post(
										`${BASEURL}/messages`,
										newMessage
									);

									console.log(response);
									alert('Success! Please refresh the browser.');
									router.replace(router.asPath);
								}
								postdata();
							}}>
							{({ errors, touched }) => (
								<Form className="contactForm">
									<Field
										name="firstname"
										placeholder="First Name"
										className="inputField"
									/>
									{errors.firstname && touched.firstname ? (
										<div className="error">{errors.firstname}</div>
									) : null}
									<Field
										name="lastname"
										placeholder="Last Name"
										className="inputField"
									/>
									{errors.lastname && touched.lastname ? (
										<div className="error">{errors.lastname}</div>
									) : null}
									<Field
										name="email"
										type="email"
										placeholder="Email"
										className="inputField"
									/>
									{errors.email && touched.email ? (
										<div className="error">{errors.email}</div>
									) : null}
									<Field
										type="textarea"
										name="message"
										component="textarea"
										placeholder="Enter your message here"
										className="textareaInput"
									/>
									{errors.message && touched.message ? (
										<div className="error">{errors.message}</div>
									) : null}

									<button className="contactBtn" type="submit">
										Submit
									</button>
								</Form>
							)}
						</Formik>
					</div>
				</div>
			</main>
			<Footer />
		</>
	);
}
