import Head from 'next/head';
import Footer from './components/footer/footer';
import { Navbar } from './components/header/header';
import Image from 'next/image';

import React from 'react';
import { Formik, Form, Field } from 'formik';
import * as Yup from 'yup';

const SignupSchema = Yup.object().shape({
	firstName: Yup.string()
		.min(2, 'Too Short!')
		.max(50, 'Too Long!')
		.required('Required'),
	lastName: Yup.string()
		.min(2, 'Too Short!')
		.max(50, 'Too Long!')
		.required('Required'),
	textarea: Yup.string()
		.min(2, 'Too Short!')
		.max(50, 'Too Long!')
		.required('Required'),
	email: Yup.string().email('Invalid email').required('Required'),
});

export default function Home() {
	return (
		<>
			<Head>
				<title>Holidaze</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
				<link
					rel="apple-touch-icon"
					sizes="180x180"
					href="/apple-touch-icon.png"
				/>
				<link
					rel="icon"
					type="image/png"
					sizes="32x32"
					href="/favicon-32x32.png"
				/>
				<link
					rel="icon"
					type="image/png"
					sizes="16x16"
					href="/favicon-16x16.png"
				/>
			</Head>
			<Navbar />
			<main>
				<div className="contact_wrapper">
					<div className="contact_ImgContainer">
						<Image
							className="contactImg"
							src="/img/hotelsbg.png"
							layout="fill"
						/>
						<h1>We are here to help</h1>
					</div>
					<div className="contact_formContainer">
						<div className="contact_headingBox">
							<h1>Contact form</h1>
							<h2>Lets get in touch</h2>
						</div>

						<Formik
							initialValues={{
								firstName: '',
								lastName: '',
								email: '',
								textarea: '',
							}}
							validationSchema={SignupSchema}
							onSubmit={(values) => {
								// same shape as initial values
								console.log(values);
							}}>
							{({ errors, touched }) => (
								<Form className="contactForm">
									<Field
										name="firstName"
										placeholder="First Name"
										className="inputField"
									/>
									{errors.firstName && touched.firstName ? (
										<div>{errors.firstName}</div>
									) : null}
									<Field
										name="lastName"
										placeholder="Last Name"
										className="inputField"
									/>
									{errors.lastName && touched.lastName ? (
										<div>{errors.lastName}</div>
									) : null}
									<Field
										name="email"
										type="email"
										placeholder="Email"
										className="inputField"
									/>
									{errors.email && touched.email ? (
										<div>{errors.email}</div>
									) : null}
									<Field
										type="textarea"
										name="textarea"
										component="textarea"
										placeholder="Enter your message here"
										className="textareaInput"
									/>
									{errors.textarea && touched.textarea ? (
										<div>{errors.textarea}</div>
									) : null}

									<button className="contactBtn" type="submit">
										Submit
									</button>
								</Form>
							)}
						</Formik>
					</div>
				</div>
			</main>
			<Footer />
		</>
	);
}
