import React from 'react';

import Head from 'next/head';
import Header from './components/header/header';

function Hotels() {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Header />
		</div>
	);
}

export default Hotels;
