import React from 'react';

import Head from 'next/head';
import Header from './components/header/header';
import Footer from './components/footer/footer';
import Herobannerhotels from './components/herobanner_hotels/herobannerhotels';

function Hotels() {
	return (
		<div>
			<Head>
				<title>Holidaze</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
				<link
					rel="apple-touch-icon"
					sizes="180x180"
					href="/apple-touch-icon.png"
				/>
				<link
					rel="icon"
					type="image/png"
					sizes="32x32"
					href="/favicon-32x32.png"
				/>
				<link
					rel="icon"
					type="image/png"
					sizes="16x16"
					href="/favicon-16x16.png"
				/>
			</Head>
			<Header />
			<Herobannerhotels />
			<main>
				<div className="hotelsHeading">
					<h3 className="hotelsHeading_h3">
						Find the perfect hotel for your destination
					</h3>
				</div>
				<input type="date"></input>
			</main>
			<Footer />
		</div>
	);
}

export default Hotels;
