import Head from 'next/head';
import Dazeclub from './components/dazeclub/dazeclub';
import Footer from './components/footer/footer';
import HeroBanner from './components/herobanner_home';
import Homecards from './components/homecards/homecards';
import Homeinfo from './components/homeinfo/homeinfo';

export default function Home() {
	return (
		<>
			<>
				<Head>
					<title>Create Next App</title>
					<meta name="description" content="Generated by create next app" />
					<link rel="icon" href="/favicon.ico" />
				</Head>
				<HeroBanner />
				<main>
					<div className="recommend_wrapper">
						<h3 className="recommend_heading">
							Hotels we recommend for our customers
						</h3>
					</div>

					<Homecards />
					<Homeinfo />
					<Dazeclub />
				</main>
			</>
			<Footer />
		</>
	);
}
