import Head from 'next/head';
import HeroBanner from './components/herobanner_home';

export default function Home() {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<HeroBanner />
		</div>
	);
}
